### ISSUE TITLE
Each 'window' needs to connect to each other and stay in the same frame

### ISSUE THREAD

**Issue by jdc29** [matteon2/agg15#3]
They are currently in different .java files. Need to be combined into one.

**Comment by waynekwokwf** [comment]
Can we link them together instead of combined into one? what is the state right now? we click on it and new java pop out? or couldn't be linked?

**Comment by jdc29** [comment]
I've checked, and from what I've seen it is (near to?) impossible to link different .java files as they each create their own GUI in a jar file. The only way to solve this is to put them all in one .java file. This has now been done. But needs to be added to for full functionality.
